from __future__ import annotations

from typing import Any


def resumir_catalogo_laudos_admin(
    db,
    *,
    filtro_busca: str = "",
    filtro_macro_categoria: str = "",
    filtro_status_tecnico: str = "",
    filtro_prontidao: str = "",
    filtro_status_comercial: str = "",
    filtro_calibracao: str = "",
    filtro_liberacao: str = "",
    filtro_template_default: str = "",
    filtro_oferta_ativa: str = "",
    filtro_mode: str = "",
    dependencies: dict[str, Any],
) -> dict[str, Any]:
    return dependencies["catalog_read_resumir_catalogo_laudos_admin"](
        db,
        filtro_busca=filtro_busca,
        filtro_macro_categoria=filtro_macro_categoria,
        filtro_status_tecnico=filtro_status_tecnico,
        filtro_prontidao=filtro_prontidao,
        filtro_status_comercial=filtro_status_comercial,
        filtro_calibracao=filtro_calibracao,
        filtro_liberacao=filtro_liberacao,
        filtro_template_default=filtro_template_default,
        filtro_oferta_ativa=filtro_oferta_ativa,
        filtro_mode=filtro_mode,
        listar_catalogo_familias=dependencies["listar_catalogo_familias"],
        listar_ofertas_comerciais_catalogo=dependencies["listar_ofertas_comerciais_catalogo"],
        listar_metodos_catalogo_fn=dependencies["listar_metodos_catalogo_fn"],
        listar_family_schemas_canonicos=dependencies["listar_family_schemas_canonicos"],
        serializar_familia_catalogo_row=dependencies["serializar_familia_catalogo_row"],
        catalog_row_matches_filters=dependencies["catalog_row_matches_filters"],
        enrich_catalog_rows_with_document_preview=dependencies["enrich_catalog_rows_with_document_preview"],
        offer_lifecycle_resolvido=dependencies["offer_lifecycle_resolvido"],
        build_template_library_rollup=dependencies["build_template_library_rollup"],
        build_material_real_rollup=dependencies["build_material_real_rollup"],
        build_commercial_scale_rollup=dependencies["build_commercial_scale_rollup"],
        build_calibration_queue_rollup=dependencies["build_calibration_queue_rollup"],
        catalog_macro_category_sort_key=dependencies["catalog_macro_category_sort_key"],
        build_catalog_governance_rollup=dependencies["build_catalog_governance_rollup"],
    )


def buscar_catalogo_familia_admin(
    db,
    family_key: str,
    *,
    dependencies: dict[str, Any],
) -> dict[str, Any] | None:
    return dependencies["catalog_read_buscar_catalogo_familia_admin"](
        db,
        family_key,
        familia_model=dependencies["familia_model"],
        oferta_model=dependencies["oferta_model"],
        modo_tecnico_model=dependencies["modo_tecnico_model"],
        calibracao_model=dependencies["calibracao_model"],
        tenant_release_model=dependencies["tenant_release_model"],
        empresa_model=dependencies["empresa_model"],
        normalizar_chave_catalogo=dependencies["normalizar_chave_catalogo"],
        offer_lifecycle_resolvido=dependencies["offer_lifecycle_resolvido"],
        dict_payload_admin=dependencies["dict_payload_admin"],
        summarize_offer_commercial_governance=dependencies["summarize_offer_commercial_governance"],
        carregar_family_schema_canonico=dependencies["carregar_family_schema_canonico"],
        catalog_family_artifact_snapshot=dependencies["catalog_family_artifact_snapshot"],
        serializar_familia_catalogo_row=dependencies["serializar_familia_catalogo_row"],
        build_template_library_rollup=dependencies["build_template_library_rollup"],
        build_material_real_workspace_summary=dependencies["build_material_real_workspace_summary"],
        catalog_offer_variants=dependencies["catalog_offer_variants"],
        listar_metodos_catalogo_fn=dependencies["listar_metodos_catalogo_fn"],
        build_document_preview_summary=dependencies["build_document_preview_summary"],
        build_variant_library_summary=dependencies["build_variant_library_summary"],
        build_material_real_priority_summary=dependencies["build_material_real_priority_summary"],
        build_template_refinement_target=dependencies["build_template_refinement_target"],
        serializar_release_catalogo_familia=dependencies["serializar_release_catalogo_familia"],
        historico_catalogo_familia=dependencies["historico_catalogo_familia"],
        resumir_governanca_review_policy=dependencies["resumir_governanca_review_policy"],
        label_catalogo=dependencies["label_catalogo"],
        lifecycle_status_labels=dependencies["lifecycle_status_labels"],
        calibration_status_labels=dependencies["calibration_status_labels"],
        calibracao_status_resolvido=dependencies["calibracao_status_resolvido"],
        catalogo_texto_leitura=dependencies["catalogo_texto_leitura"],
        catalogo_actor_label=dependencies["catalogo_actor_label"],
        catalogo_modelo_label=dependencies["catalogo_modelo_label"],
        formatar_data_admin=dependencies["formatar_data_admin"],
        normalizar_datetime_admin=dependencies["normalizar_datetime_admin"],
    )


def upsert_tenant_family_release(
    db,
    *,
    tenant_id: int,
    family_key: str,
    release_status: str,
    allowed_modes: list[str] | tuple[str, ...] | str | None = None,
    allowed_offers: list[str] | tuple[str, ...] | str | None = None,
    allowed_templates: list[str] | tuple[str, ...] | str | None = None,
    allowed_variants: list[str] | tuple[str, ...] | str | None = None,
    force_review_mode: str = "",
    max_review_mode: str = "",
    mobile_review_override: str = "",
    mobile_autonomous_override: str = "",
    release_channel_override: str = "",
    included_features_text: str = "",
    entitlement_monthly_issues: int | str | None = None,
    entitlement_max_admin_clients: int | str | None = None,
    entitlement_max_inspectors: int | str | None = None,
    entitlement_max_reviewers: int | str | None = None,
    entitlement_max_active_variants: int | str | None = None,
    entitlement_max_integrations: int | str | None = None,
    default_template_code: str = "",
    observacoes: str = "",
    criado_por_id: int | None = None,
    dependencies: dict[str, Any],
):
    return dependencies["catalog_tenant_upsert_release"](
        db,
        tenant_id=tenant_id,
        family_key=family_key,
        release_status=release_status,
        allowed_modes=allowed_modes,
        allowed_offers=allowed_offers,
        allowed_templates=allowed_templates,
        allowed_variants=allowed_variants,
        force_review_mode=force_review_mode,
        max_review_mode=max_review_mode,
        mobile_review_override=mobile_review_override,
        mobile_autonomous_override=mobile_autonomous_override,
        release_channel_override=release_channel_override,
        included_features_text=included_features_text,
        entitlement_monthly_issues=entitlement_monthly_issues,
        entitlement_max_admin_clients=entitlement_max_admin_clients,
        entitlement_max_inspectors=entitlement_max_inspectors,
        entitlement_max_reviewers=entitlement_max_reviewers,
        entitlement_max_active_variants=entitlement_max_active_variants,
        entitlement_max_integrations=entitlement_max_integrations,
        default_template_code=default_template_code,
        observacoes=observacoes,
        criado_por_id=criado_por_id,
        buscar_empresa=dependencies["buscar_empresa"],
        buscar_familia_catalogo_por_chave=dependencies["buscar_familia_catalogo_por_chave"],
        tenant_release_model=dependencies["tenant_release_model"],
        normalizar_status_release_catalogo=dependencies["normalizar_status_release_catalogo"],
        normalizar_lista_json_canonica=dependencies["normalizar_lista_json_canonica"],
        normalizar_selection_tokens_catalogo=dependencies["normalizar_selection_tokens_catalogo"],
        merge_release_governance_policy=dependencies["merge_release_governance_policy"],
        normalizar_review_mode_governanca=dependencies["normalizar_review_mode_governanca"],
        normalizar_override_tristate=dependencies["normalizar_override_tristate"],
        normalizar_release_channel_catalogo=dependencies["normalizar_release_channel_catalogo"],
        normalizar_contract_entitlements_payload=dependencies["normalizar_contract_entitlements_payload"],
        normalizar_chave_catalogo=dependencies["normalizar_chave_catalogo"],
        agora_utc=dependencies["agora_utc"],
        normalizar_texto_opcional=dependencies["normalizar_texto_opcional"],
        list_active_tenant_catalog_activations=dependencies["list_active_tenant_catalog_activations"],
        sync_tenant_catalog_activations=dependencies["sync_tenant_catalog_activations"],
        flush_ou_rollback_integridade=dependencies["flush_ou_rollback_integridade"],
        logger_operacao=dependencies["logger_operacao"],
    )


def resumir_portfolio_catalogo_empresa(db, *, empresa_id: int, dependencies: dict[str, Any]) -> dict[str, Any]:
    return dependencies["catalog_tenant_resumir_portfolio"](
        db,
        empresa_id=empresa_id,
        build_admin_tenant_catalog_snapshot=dependencies["build_admin_tenant_catalog_snapshot"],
    )


def sincronizar_portfolio_catalogo_empresa(
    db,
    *,
    empresa_id: int,
    selection_tokens: list[str] | tuple[str, ...],
    admin_id: int | None = None,
    dependencies: dict[str, Any],
) -> dict[str, Any]:
    return dependencies["catalog_tenant_sincronizar_portfolio"](
        db,
        empresa_id=empresa_id,
        selection_tokens=selection_tokens,
        admin_id=admin_id,
        buscar_empresa=dependencies["buscar_empresa"],
        sync_tenant_catalog_activations=dependencies["sync_tenant_catalog_activations"],
        flush_ou_rollback_integridade=dependencies["flush_ou_rollback_integridade"],
        logger_operacao=dependencies["logger_operacao"],
    )
